### ISSUE TITLE
Batch processing and numeric key

### ISSUE THREAD

**Issue by lwillems** [recombee/php-api-client#11]
When using Batch() with numeric keys in array body, everything is replaced by other keys due to $params = array_merge($params, $req->getBodyParameters()) in RequestBatchArray() method

So numeric keys can not be used

Regards

**Comment by OndraFiedler** [comment]
Can you please give a sample code of such a usage?

**Comment by lwillems** [comment]
Not tested but should fail with error unknown property 0

```php
$client = new Client('--my-database-id--', '--my-secret-token--');
$client->send(new Reqs\AddItemProperty('price', 'double'));
$client->send(new Reqs\AddItemProperty(45, 'int'));

$requests = array();
for($i=0; $i<NUM; $i++)
{
    $itemId = "computer-{$i}";
    $r = new Reqs\SetItemValues(
      $itemId,
      //values:
      [ 
        'price' => rand(15000, 25000),
        45 => rand(1, 8),
      ],
      //optional parameters:
      ['cascadeCreate' => true] // Use cascadeCreate for creating item
                                 // with given itemId, if it doesn't exist]
    );
    array_push($requests, $r);
}

$result =  $client->send(new Reqs\Batch($requests));
var_dump($result);

**Comment by OndraFiedler** [comment]
@lwillems But the names of the properties (columns) can only be strings, so this is not valid anyway, right?

**Comment by lwillems** [comment]
https://github.com/recombee/php-api-client/pull/12

**Comment by lwillems** [comment]
i was not aware of string only, is it in documentation ?

**Comment by OndraFiedler** [comment]
https://docs.recombee.com/api.html#add-item-property states, that `propertyName` must is a string.
I think that what is not very nice, is that the endpoint silently converted `45` to `"45"` and created the property, instead of returning HTTP 400. This should be fixed in the API.
