### ISSUE TITLE
Missing info in batch reply

### ISSUE THREAD

**Issue by lwillems** [recombee/php-api-client#14]
According API documentation when using batch response looks like this 

```json
[
  {
    "code": 200,
    "json": "ok"
  },
  {
    "code": 200,
    "json": "ok"
  },
  {
    "code": 200,
    "json": [
      "item-a",
      "item-b",
      "item-c",
      "item-d",
      "item-e"
    ]
  }
]
```
But when i am using it  with multiple setItemsValues, reply looks like this 

```json
[
  {
    "json": "ok",
    "code": 200
  },
  {
    "json": "ok",
    "code": 200
  }
]
```
Last part with my itemId is missing, so i am not able to determine which items are ok and which ones are failed.

Regards,

**Comment by OndraFiedler** [comment]
You have two SetItemValues requests in the Batch right? So first 
```
  {
    "json": "ok",
    "code": 200
  }
```
in the array is reply for the first SetItemValues request and the second reply for the second request.

**Comment by OndraFiedler** [comment]
> how to be sure that order in reply will be always the same one than POST body order ?

It is guaranteed (requests are sent also in an array with order, and this order is kept in the response).

> in recombee documentation it seems there is also an array with original itemId,

In the example in docs third request in Batch is User Based Recommendation request and this is response to it (recommended items). It is not response to a Set Item Values request.
You can mix in the Batch any requests.
