### ISSUE TITLE
Support PSR-18

### ISSUE THREAD

**Issue by staabm** [recombee/php-api-client#19]
as it stands this lib requires the rmccue/requests http client.

to ease integration into existing applications/frameworks it would be very helpfull if the lib instead would use the PSR18 interfaces instead of a concrete http client.
that way the lib could be used with a already existing http client lib and would not need to add an additional http client to an existing stack.

thats a major pain point when using the lib

https://www.php-fig.org/psr/psr-18/

**Comment by OndraFiedler** [comment]
As mentioned in https://github.com/recombee/php-api-client/issues/22#issuecomment-775747142, it does not seem to be possible to set timeout per request in an HTTP client agnostic way using PSR-18, which is a blocking issue.
