### ISSUE TITLE
Problems while installing the php-api-client 3.1

### ISSUE THREAD

**Issue by staabm** [recombee/php-api-client#22]
we are running into problems because of the guzzle dependency in the 3.1 version of this lib.

our dependency graph already contains the guzzle http client and therefore our dependency constraint conflict with those defined in https://github.com/recombee/php-api-client/blob/a9fcf9c60c2da7f48174c0a57516586344b6a5fc/composer.json#L14

could this package be adapted to use https://github.com/php-http/httplug instead of guzze directly?
httplug is a small abstraction layer - which is also implemented by guzzle - but allows switching the http client in use. that way the recombee php api client would not directly depend on a fixed http client implementation and therefore it would be easier to integrate it into existing applications

**Comment by staabm** [comment]
as an example you might look at https://github.com/KnpLabs/php-github-api which uses the http-plug and addtionally uses guzzle as a require-dev only dependency for the testsuite

**Comment by OndraFiedler** [comment]
Thanks for the report, we will look into it.

**Comment by OndraFiedler** [comment]
One of the key features of the Recombee PHP SDK is that it throws `ApiTimeoutException` when the request does not finish in time.
The timeout is specific for each type of request, and there is some logic for the timeout of the Batch based on the requests included in the Batch.
Throwing this exception depends on setting timeout per request to the HTTP library and on handling the exception it produces when the timeout happens.

However, it seems that https://github.com/php-http/httplug  does not provide such abstraction: https://github.com/php-http/httplug/issues/131.

@staabm do you have some idea how to overcome this?

**Comment by staabm** [comment]
Hey Ondra.

thx for coming back to me.

after reading into the details, I feel like what you are searching for is defined in PSR-18, which httplug claims to implement

https://www.php-fig.org/psr/psr-18/

> If a request cannot be sent because the request message is not a well-formed HTTP request or is missing some critical piece of information (such as a Host or Method), the Client MUST throw an instance of Psr\Http\Client\RequestExceptionInterface.
>
> If the request cannot be sent due to a network failure of any kind, including a timeout, the Client MUST throw an instance of Psr\Http\Client\NetworkExceptionInterface.
>
> Clients MAY throw more specific exceptions than those defined here (a TimeOutException or HostNotFoundException for example), provided they implement the appropriate interface defined above.

**Comment by OndraFiedler** [comment]
> I feel like what you are searching for is defined in PSR-18, which httplug claims to implement

I think that enables us to catch an exception from the HTTP client.
However, I don't see a way how to (with httplug/PSR) set timeout per request in an HTTP client agnostic way.
@staabm Do you see a way how to resolve this?

**Comment by OndraFiedler** [comment]
@staabm As it seems, that switching to httplug/PSR-18 might not be so straightforward, would changing the dependency to:
```
"guzzlehttp/guzzle": "^6.0.0 || ^7.0.0"
```
fix your issues?

We would test the compatibility with Guzzle 6 before releasing the change.
Older versions of Guzzle are EOL.

**Comment by staabm** [comment]
> We would test the compatibility with Guzzle 6 before releasing the change.
> Older versions of Guzzle are EOL.

this sounds great. our current issue is

```
$ composer update
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires complex/rocket dev-CLX6_2020R03 -> satisfiable by complex/rocket[dev-CLX6_2020R03].
    - complex/rocket dev-CLX6_2020R03 requires complex/clxdeployer-recipies ^2.7 -> satisfiable by complex/clxdeployer-recipies[2.7.0, ..., 2.9.15].
    - complex/clxdeployer-recipies[2.7.0, ..., 2.9.15] require php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1].
    - php-http/guzzle6-adapter[v1.1.0, ..., v1.1.1] require guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, ..., 6.5.5].
    - You can only install one version of a package, so only one of these can be installed: guzzlehttp/guzzle[6.0.0, ..., 6.5.5, 7.2.0].
    - recombee/php-api-client v3.1.0 requires guzzlehttp/guzzle ^7.2.0 -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - Root composer.json requires recombee/php-api-client ^3.1 -> satisfiable by recombee/php-api-client[v3.1.0].
```

so the conflict is guzzle v6 vs. v7. having compat in this lib with v6 should resolve it.

**Comment by OndraFiedler** [comment]
Support for Guzzle 6 has been added in [v3.2.0](https://github.com/recombee/php-api-client/releases/tag/v3.2.0).
