### ISSUE TITLE
Client hides all connection errors as ApiTimeoutException; can't include previous Exception instance

### ISSUE THREAD

**Issue by magus424** [recombee/php-api-client#23]
Even things like an SSL error will report as timeout, which can easily cause confusion when attempting to debug.

`ApiTimeoutException`, `ResponseException`, and `UnknownOptionalParameterException` are also missing backslashes on `Exception` in their constructors, which prevent one from attempting to pass the previous exception in to help indicate the root problem; PHP will fail expecting an instance of `Recombee\ReommApi\Exceptions\Exception` which does not exist

**Comment by OndraFiedler** [comment]
Thanks for the report and fix.
We have tested it and released it in [v3.2.1](https://github.com/recombee/php-api-client/releases/tag/v3.2.1).
