### ISSUE TITLE
Batch method and the problem with identifying original request 

### ISSUE THREAD

**Issue by lukasojd** [recombee/php-api-client#25]
Hi, 
I have a problem. I use us library. I would like to use the batch method. I can not pair original requests on responses. I get only an array without an identification on original request. 

Example currently state: 
```
<?php

declare(strict_types=1);

use Recombee\RecommApi\Client;
use Recombee\RecommApi\Requests\Batch;
use Recombee\RecommApi\Requests\SearchItems;

$client = new Client('--my-database-id--', '--db-private-token--');

$requests = [
	new SearchItems(user_id: '12345', search_query: 'test', count: 10),
	new SearchItems(user_id: '12345', search_query: 'test1', count: 10),
	new SearchItems(user_id: '12345', search_query: 'test2', count: 10)
];

$batch = new Batch($requests);

$output = $client->send($batch); // I get only array without reference on some requests
```

**Comment by OndraFiedler** [comment]
Can you please clarify what do you mean by "an array without an identification"? What are you missing?
It is expected to get back an array of replies (see https://docs.recombee.com/api.html#batch)
