### ISSUE TITLE
PHP SDK does not work

### ISSUE THREAD

**Issue by AdamMiltonBarker** [recombee/php-api-client#31]
Following your documentation here, including installing the client sdk: https://github.com/Recombee/php-api-client

PHP Fatal error:  Uncaught InvalidArgumentException: Region  is unknown. You may need to update the version of the SDK.

Removing region array results in Uncaught Recombee\RecommApi\Exceptions\ResponseException: {"statusCode":404, "message":"Unable to parse database"} when using the credentials provided in your UI.

**Comment by AdamMiltonBarker** [comment]
Resolved this but now   Uncaught Error: Class "AddUser" not found when using $client->send(new AddUser($user_id));

**Comment by OndraFiedler** [comment]
Can you please share what was the issue?

Regarding the latter issue, it will be probably connected to the import of the `Requests`.

```php

use Recombee\RecommApi\Requests as Reqs;

...

$req = new Reqs\AddUser("user1");
```

Please see the code examples for more info.

**Comment by AdamMiltonBarker** [comment]
The code examples that I found for AddUser do not have Reqs\AddUser on AddUser, I just worked this out so all good.

**Comment by AdamMiltonBarker** [comment]
Sorry thought I had resolved it, Reqs/AddUser gives Uncaught Recombee\RecommApi\Exceptions\ResponseException: {"error": "Method not allowed.", "statusCode": 405, "statusMessage": "method not allowed"}

**Comment by AdamMiltonBarker** [comment]
Will not work, I have been able to import items but using the same credentials I get 

Fatal error:  Uncaught Recombee\RecommApi\Exceptions\ResponseException: {"error": "Method not allowed.", "statusCode": 405, "statusMessage": "method not allowed"} in /home/cognitech/vendor/recombee/php-api-client/src/RecommApi/Client.php:216

$req = new Reqs\AddUser(USER);
$client->send($req);

**Comment by AdamMiltonBarker** [comment]
@OndraFiedler  do you have an update on this?

**Comment by OndraFiedler** [comment]
The most probable reason is passing an empty or NULL `userId`, leading to a wrong URL of the REST call.
Can you please check what is being passed to `AddUser`?
