### ISSUE TITLE
PHP 8.3 deprecation error

### ISSUE THREAD

**Issue by kergekacsa** [recombee/php-api-client#32]
There is a deprecation error with PHP 8.3:

Deprecated: Creation of dynamic property Recombee\RecommApi\Requests\Batch::$optional is deprecated in /web/vendor/recombee/php-api-client/src/RecommApi/Requests/Batch.php:39

$this->optional is not defined in the Request class before used here:
[https://github.com/recombee/php-api-client/blob/master/src/RecommApi/Requests/Batch.php#L39](https://github.com/recombee/php-api-client/blob/master/src/RecommApi/Requests/Batch.php#L39)

**Comment by OndraFiedler** [comment]
@kergekacsa Thanks for the report!

The issue has been fixed in version 4.1.2.
