### ISSUE TITLE
No actions being stored

### ISSUE THREAD

**Issue by AdamMiltonBarker** [Recombee/php-api-client#4]
Hi I am using PHP api and have successfully added products and views and received recommendations, when publishing views and add to cart actions, none of these are showing up in the console, in addition, when clicking on a recommended product which sends a view detail, the view details are not showing up, also after a while recommendations return nothing.

View details, add to cart etc all return OK, I see the 2 products and the two users in the console but clicking on them shows none of the actions, actions do not show up on the graphs either.

**Comment by AdamMiltonBarker** [comment]
Sorry, I do see in the catalog list now that you can change the type via the dropdown, however, in KPI, it still shows 0 actions.

**Comment by OndraFiedler** [comment]
Hi,

an action means that you get recommendations for user, and the user then views a recommended item. It seems you don't have such sequence in your database.

The user based recommendation by default excludes all the interacted (viewed, purchased...) items. The item based recommendation by default do not exclude.

These defaults have reasoning, but it may seem bit confusing when you have that small number of items (you can run out of them in case of user based recommendation), so I suggest you upload larger number of interactions and items (you can use Batch request for faster processing).

**Comment by AdamMiltonBarker** [comment]
Thanks for the quick reply. Unfortunately we are not in the position to upload bulk data, it is being built on a totally new system where we do not have the data available.

Ok yes it is very confusing there does not seem to be a standard way it works, I have now purchased all three products and it still shows all three on a user based recommendation on one page even though I have viewed, added to cart and purchased them.

Then on an item based recommendation it now shows 0 which seems to be correct as I have actioned on them all. 

To add products to the database, it is possible when a client uploads a product to store it in the database automatically so that people will see them before visiting a page ?

Also UserBasedRecommendation gives error on a new user, is it possible to use cascadeCreate on UserBasedRecommendation ?

**Comment by AdamMiltonBarker** [comment]
I found it is possible to use cascadeCreate on UserBasedRecommendation and ItemBasedRecommendation no worries on that side.

**Comment by AdamMiltonBarker** [comment]
Just a quick question about limits also, is it only the recommendations that apply to your limits or is it every interaction, IE views, add to carts, purchase etc, just so I can build in a system that can limit it from the application side.

**Comment by AdamMiltonBarker** [comment]
Ok so now, with no changes, it is suddenly showing me two of the products I have already bought, viewed and added to cart on the item based rec.

**Comment by OndraFiedler** [comment]
Only recommendations count into 100k limit of a free account.

> Ok so now, with no changes, it is suddenly showing me two of the products I have already bought, viewed and added to cart on the item based rec.

Can you be please more specific about for which user/item you are experiencing weird behavior so I can check it?

> To add products to the database, it is possible when a client uploads a product to store it in the database automatically so that people will see them before visiting a page ?

Sorry, I don't understand the question :)

**Comment by AdamMiltonBarker** [comment]
Sure currently user-1, which has purchased product 1, 2 and 3, and viewed them and added them to cart. On a user based rec I see all three, actually scratch that, I now do not see them, but this was definitely not real time.

On item based rec, when viewing product 3 I see recommendations for 1 and 2, when viewing 2 I see 1 and 2 etc etc

**Comment by AdamMiltonBarker** [comment]
RE the last part, when a client is adding their products to the cart can we add the product to the database on your platform so that people can see them, currently unless a person has viewed a product, it does not exist until a user views it and therefore is not recommended

**Comment by OndraFiedler** [comment]
> when a client is adding their products to the cart can we add the product to the database on your platform so that people can see them, currently unless a person has viewed a product, it does not exist until a user views it and therefore is not recommended

Will cascadeCreate on iteractions help?

**Comment by AdamMiltonBarker** [comment]
Going back to comment above:

 It seems you don't have such sequence in your database.

The sequence has happened many times yet still says 0, 83 recommendations, 0 actions, Conversions 0, despite multiple add to carts, views and purchases.

**Comment by AdamMiltonBarker** [comment]
No that will not help, as someone has to view the product before it is indexed in the database.

**Comment by AdamMiltonBarker** [comment]
OK so here is flow, will mark each step by step:

New user -> User based works correctly
Visit one of recommendations -> User based rec still shows that item
Add that item to cart -> User based rec still shows that item
Buy that item (Logged in as user-1 now, flips from cookie based ID to user) -> No items shown in user based which is correct. Viewing a different item still shows the item I bought and the other one.

**Comment by AdamMiltonBarker** [comment]
I now have conversions, 6 of them which suddenly appeared, but still no actions.

**Comment by OndraFiedler** [comment]
> The sequence has happened many times yet still says 0, 83 recommendations, 0 actions, Conversions 0, despite multiple add to carts, views and purchases.

The sequence recommendation -> view has not happened, but the sequence recommendation -> purchase (=conversion) has, and you can see these conversion in the interface.

**Comment by OndraFiedler** [comment]
Ad the recommendations:
The behavior for item based recommendation seems correct to me (recommending {product-3,product-2}	
 to product-1, {product-1,product-3} for product-2 ...). Why do you think it's incorrect?

The user based recommendation may look bit strange at first sight, but I think that it's because the system also penalize items for being recently recommended (in order to show new content to the user). You can turn this off by specifying rotationRate = 0 in the user based recommendation requests. Again, it is strange mainly because you have only few items and the configuration (rotations, excludes...) assume much larger data. If you don't have your own, you can try for example one of those: https://gist.github.com/entaroadun/1653794.

> Client uploads their product -> Send API call to your platform to add the product -> Users automatically see the product in their recommendations.

If you want to make sure that new products appear in the recommendations, you can boost them using ReQL https://docs.recombee.com/reql.html.

**Comment by AdamMiltonBarker** [comment]
The sequence recommendation -> view  has happened many many times, this is what I am trying to tell you, both of the last purchases specifically and others before, I visited the product directly from a recommendation, added it to cart directly from that visit, and then checked out directly from that add to cart. 

Also why are the item based recs not working correctly?

**Comment by AdamMiltonBarker** [comment]
I will repeat that process right now, logged in as user-1:

Currently on product 3, recommendations for product 1 and 2 are visible.
Click on recommendation for product 1 -> add to cart -> checked out

Go back to product 3 -> recommendation for product 2 and 3 still exist, user based rec 0 recs exist

Refresh KPI -> 0 actions

**Comment by OndraFiedler** [comment]
Ad actions: Do you specify some exact timestamp in the views? It seems that there sequences recommendation -> view but not within 30 minutes (which is our current default limit for action), co maybe the timestamps are wrong. You can leave the timestamp unset to use the current.

**Comment by AdamMiltonBarker** [comment]
time stamp is set in the form of YYYY-MM-DD H:i:s, there are many views from recs that have been done within the last half an hour, a large amount total today.

**Comment by OndraFiedler** [comment]
Ok, try it without setting exact timestamp (do not specify the optional parameter) to confirm that the timestamp are the issue

**Comment by AdamMiltonBarker** [comment]
ok one sec

**Comment by AdamMiltonBarker** [comment]
Ok back on product 3 -> recs for product 1 and 2 show
Click on product 1 -> add to cart -> checkout

Back to product 3 -> product 1 and 2 still show, but actions now show 3.

Must of been time difference between my server and yours. 

So only the item based recs issue now :)

**Comment by OndraFiedler** [comment]
It's the problem of timezones, I think we assume +0 if not specified, and you are probably not in that timezone. Maybe using UTC timestamp is more convenient.

**Comment by AdamMiltonBarker** [comment]
I am in Spain, server is in Holland, as long as it works without the timestamp no issues, is this related to the item based recs? Why are the user based recs working correctly but not item based ?

**Comment by OndraFiedler** [comment]
What is the problem with item based recommendations?

**Comment by AdamMiltonBarker** [comment]
I mentioned it a few times above:

Ok back on product 3 -> recs for product 1 and 2 show
Click on product 1 -> add to cart -> checkout

Back to product 3 -> PRODUCT 1 and 2 STILL SHOW

This is repeating constantly on all pages, user based recs show none now, but item based user recs, where I provide target user are incorrect, they should not show any now.

**Comment by AdamMiltonBarker** [comment]
Any info on the above? Also would it be possible to change how the system views an item a user has used, it would make more sense to not show items a person has bought rather than the not showing the ones they have viewed, they may view a product and want to come back to it at a later date, reminding them of a product that they have viewed but not bought seems like a good idea.

**Comment by OndraFiedler** [comment]
I think the item based recommendation behaves according to default behavior of the item based recommendation that I have already described - it does not exclude the interacted items (from our experience most customers don't want to exclude the items that have been interacted from the related products). All these rules are fully customizable per database on our side if you choose to use the standard account.

**Comment by AdamMiltonBarker** [comment]
If it goes well during our testing we will include it in our packages with a free and paid option, so yes that is a possibility, sorry I missed where you mentioned about item based not excluding. Ok thanks for the help.
