### ISSUE TITLE
Invalid HMAC signature

### ISSUE THREAD

**Issue by wasimkham** [recombee/php-api-client#7]
Trying to use the PHP API client and I'm getting an error when running any command.

```
[Recombee\RecommApi\Exceptions\ResponseException]
  {"statusCode":401, "error":"Invalid HMAC signature"}
```

I've set it up exactly how it says in the docs.

```
$client = new Client(
            config('services.recombee.database'),
            config('services.recombee.token')
        );

$client->send(new AddItemProperty("name", "string"));
```

I've searched your API docs and it says the APIs take care of the HMAC signature already. Can you help with this issue please?

**Comment by OndraFiedler** [comment]
I'm glad you solved it :+1:

**Comment by wasimkham** [comment]
@OndraFiedler My bad, I was using the original token when I started the account, not knowing there was a different token for each new database created.
