### ISSUE TITLE
Empty json response is evaluated as false

### ISSUE THREAD

**Issue by marcusklaas** [recombee/php-api-client#8]
Whenever item-based recommendations are requested with a minimum relevance greater than `low`, it is possible that the result set is empty.

It seems that this is interpreted as a malformed json [here](https://github.com/recombee/php-api-client/blob/master/src/RecommApi/Client.php#L157-L161), when it is in fact a valid response.

The client then returns a string type instead of an array, which is unexpected.

**Comment by Timvd** [comment]
@marcusklaas this pr should fix this issue : https://github.com/recombee/php-api-client/pull/9

**Comment by OndraFiedler** [comment]
Thanks @Timvd for fixing and @marcusklaas for reporting the bug. I just released version  [2.0.1](https://github.com/recombee/php-api-client/releases/tag/v2.0.1 ) with merged code.
